language: scala

sudo: false

services:
   - postgresql

addons:
  postgresql: "9.6"

scala:
  - 2.12.4

jdk:
  - oraclejdk8

script:
  - sbt ';clean;coverage;domain/test;migration/test;core/test;telegram/test;coverageReport'

#notifications:
#  webhooks:
#    urls:
#    - https://webhooks.gitter.im/e/dd8738e10fa36a15a4d8
#    on_success: change
#    on_failure: always
#    on_start: false

before_script:
  - find modules/migration/src/main/resources/db/migration/ -name *.sql -exec psql -U postgres -f {} \;

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
  - $HOME/.sbt/0.13/dependency
  - $HOME/.sbt/boot/scala*
  - $HOME/.sbt/launchers
  - $HOME/.ivy2/cache
  - $HOME/.nvm

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete