version: '3.2'
services:
  db:
    image: postgres:9
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ./modules/migration/src/main/resources/db/migration
        target: /docker-entrypoint-initdb.d